version: 1.2
workflows:
  - name: seqkitStats
    subclass: WDL
    primaryDescriptorPath: /seqkit_stats_wdl/seqkitStats.wdl
    authors:
      - orcid: 0000-0001-5736-3193
  - name: happyEval
    subclass: WDL
    primaryDescriptorPath: /happy_wdl/happy_evaluation.wdl
  - name: flye
    subclass: WDL
    primaryDescriptorPath: /flye_wdl/Flye.wdl
  - name: quastOutput
    subclass: WDL
    primaryDescriptorPath: /shasta_eval/quast_output.wdl


